workspace = { members = ["src/util/macros"] }

[package]
name = "nea"
version = "0.2.0"
edition = "2021"


[dependencies]
egui = "0.21.0"
eframe = "0.21.3"
tracing-subscriber = "0.3"
strum = "0.24.1"
strum_macros = "0.24.3"
libm = "0.2.6"
